#!/bin/bash

/home/ec2-user ---- root user
SESSION-1

SDLC
======
Software Development Lifecycle
Business Analyst
===============
Business
Requirements gathering
Planning and Designing
Implementation
Deployment
Testing
Release into public
Maintanance

Waterfall
===========
Stakeholders --> Who is part of the system 
School Management System
------------------------
Teachers Students Parents Staff(Principal) Investors and Management Government

in our family stakholders --> GF,GM,dad,mother,siblimgs&me
EX:1
100 years ( Gurukul Model)
Students -> they don't read from DAY-1
Teachers -> they don't teach from DAY-1
Parents -> They worry from DAY-1
Grand Finale exams
Pass persentage 20-30%
why 70% failed

Problems
=========
1. only exam time. scared about exam
2. teachers wont ask to study seriously
3. Parents wont raise quetions to teachers
So after some years, 
Changes had been done
==========
UNIT Tests - I, II, III, IV
Quarterly, Half yearly, Pre-Final
So here Students chadavatum start chesaru and as well exam medha fear kuda konchem poindi.
so final ga pass percentage 75% 
--> Again some chanages had been done
Changes
=========
Slip/Daily tests
365 days
200 days
150 slip tests

Pass 95%
Gurukul -> Waterfall
Unit test --> Agile
Daily Tests -> DevOps

Waterfall
=========
client given time 2 years --> 100cr budget
so here employess work ni serious ga tisukoru  ala 1 year timepass chesi next 1 year work chesaru andhulo development 6 months ans 6 testing so finla ga clint ki iste then clinet not satisfied because 
100 defects --> 10 invalid defects in that has some errors, clinet has been get loss their business
Client expert chesindi gold anukunte vallu icchendi silver. so ala

---> So final ga they had some changes
Agile
=========
Sprint basis
Clinet given to work like as below

Signup Login
Product management
Order management
Shipping and delivery
Payment
Reviews

SPRINT-1
========
Signup and Login

1 month

15 days development
15 days testing and deployment

10 -> 2 invalid defects
here develop and testing teams gathered to fix the bugs at same time 

development and testing is improved

expert level Ferrari --> Honda City

SPRINT-2
========
Product management
Backlog and bug fixing
everyday calls and discussions 
works going good for clinet
satisfied here
Final product was happened

DevOps
=======
Development --> DEV and SIT Deploy(Build and Release) --> Testing

Whatever the code developed by developer should be tested and deployed on the same days

Signup form
===========
Enter your firstname
Enter your lastname

2 defects -> 1 invalid defects
here develop and testing teams gathered to fix the bugs at same time
development and testing is improved 
DevOps is the combination of "development" and "operations" 
the process of developing, building, deploying, and testing on the same day, which can improve coordination between all the teams and as well as breaking down the traditional separation between them. We use multiple DevOps tools to achieve this. Configuration management, CICD, with high quality etc.